#!/usr/bin/env python

# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///

from typing import Any
import argparse
import sys
import xml.etree.ElementTree as ET

# "uv tool run mypy --strict kwallet-extractor" for type checking
def main() -> None:
    # parse cmdline args
    parser = argparse.ArgumentParser(
            description='Extracts passwords and credentials from KWallet XML files'
            )
    parser.add_argument('-a', '--all-fields', action='store_true',
                        help='Extract from all KWallet folders, not just "Passwords"')
    parser.add_argument('input',
                        help='Path to XML export to read')

    args = parser.parse_args()

    try:
        root = parse_xml(args.input)
    except Exception as e:
        # Some kind of error encountered
        print(f"Ran into an error while reading {args.input}:\n{e}")
        sys.exit(1)

def parse_xml(filename: str) -> ET.Element:
    tree = ET.parse(filename)
    root = tree.getroot()

    if root.tag != "wallet":
        raise Exception(f"The wallet XML had the wrong root element! Expected <wallet>, got <{root.tag}>")

    return root

if __name__ == "__main__":
    main()
